### ISSUE TITLE
Create the list vendor card component

### ISSUE THREAD

**Issue by owonwo** [wigxel/rest-event-frontend#7]
Create the stack VendorCard from the vendor parent profile. 

- [x] Designed the VendorCard
- [x] Created component has the following props: 
1. banner
2. logo
3. name
4. isPremium
5. rating
6. description

**Comment by NotJohs** [comment]
@owonwo where does this card fall into... where is it in the design?

**Comment by owonwo** [comment]
I'll update it soon.
